### ISSUE TITLE
Lỗi cmanga

### ISSUE THREAD

**Issue by Karuto2k7** [kur21/vbook-ext#2]
![Screenshot_20241031_014336_vBook App](https://github.com/user-attachments/assets/4a814579-c02e-4da9-b150-fdf09616ee40)

Đã thử đổi domain và lỗi JavaScript #17

**Comment by kur21** [comment]
lỗi này do bên cmanga chặn bằng cloudflare để tránh auto crawl, cái này bạn bấm vào dấu 3 chấm góc phải phía trên, rồi vào web bằng trình duyệt của app để bypass cloudflare, sau đó bạn trở ra là load lại đc data nhé. Cái này bên Cmanga nó chặn thì lách vậy thui :)))

**Comment by Karuto2k7** [comment]
> lỗi này do bên cmanga chặn bằng cloudflare để tránh auto crawl, cái này bạn bấm vào dấu 3 chấm góc phải phía trên, rồi vào web bằng trình duyệt của app để bypass cloudflare, sau đó bạn trở ra là load lại đc data nhé. Cái này bên Cmanga nó chặn thì lách vậy thui :))) Lâu lâu nó sẽ bị 1 lần, cứ làm như trên thui bạn ơi. Hoặc cho đến khi cmanga bỏ cái chặn cái đó thui

Cái này mình bị là nó chặn hẳn ý bạn còn cái vụ cloudflare thì mình đã thử trc khi báo bạn r nhé 🤡 
@kur21 

https://github.com/user-attachments/assets/121bf660-b259-4c41-a486-8eb1cd3d667a

**Comment by kur21** [comment]
> > lỗi này do bên cmanga chặn bằng cloudflare để tránh auto crawl, cái này bạn bấm vào dấu 3 chấm góc phải phía trên, rồi vào web bằng trình duyệt của app để bypass cloudflare, sau đó bạn trở ra là load lại đc data nhé. Cái này bên Cmanga nó chặn thì lách vậy thui :))) Lâu lâu nó sẽ bị 1 lần, cứ làm như trên thui bạn ơi. Hoặc cho đến khi cmanga bỏ cái chặn cái đó thui
> 
> Cái này mình bị là nó chặn hẳn ý bạn còn cái vụ cloudflare thì mình đã thử trc khi báo bạn r nhé 🤡 @kur21
> 
>  mobizen_20241112_063744.mp4

Mình tìm đc nguyên nhân rồi, do bên trình duyệt của app, bạn chịu khó chuyển sang xem dạng máy tính là đc nha. Vì mình làm ext trên giao diện desktop :)))) bạn thử xem oki ko nhé.

https://github.com/user-attachments/assets/112364b8-9ff2-4aa6-a7c5-50fe9058a0e6
